# This is a basic workflow to help you get started with Actions

name: docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Get dependecies
        run: npm ci

      # Runs a set of commands using the runners shell
      - name: Build docs
        run: npm run docs:build
      
      - name: Install and configure s3cmd
        run: |
          sudo apt-get install -y s3cmd
          touch ~/.s3cfg
          echo "[default]
          # Object Storage Region NL-AMS
          host_base = s3.fr-par.scw.cloud
          host_bucket = %(bucket)s.s3.fr-par.scw.cloud
          bucket_location = fr-par
          use_https = True

          # Bucket Website feature configuration (https://www.scaleway.com/en/docs/s3-bucket-website-console/)
          website_endpoint = https://%(bucket)s.s3-website.%(location)s.scw.cloud/
          website_index = index.html # Website index filename
          website_error = 404.html # Website error filename
          # Login credentials
          access_key = ${{ secrets.SCALEWAY_ACCESS_KEY_ID }}
          secret_key = ${{ secrets.SCALEWAY_SECRET_ACCESS_KEY }}" > ~/.s3cfg
          

      - name: Deploy static site to S3 bucket
        run: s3cmd --acl-public sync —delete-removed ./docs/.vuepress/dist/  s3://vuepress
